### ISSUE TITLE
Letting bots build dome destroys it?

### ISSUE THREAD

**Issue by YarrikV** [notnotmelon/maraxsis#91] opened 2024-12-09 15:36 UTC
I place a ghost of a dome, which I have in my inventory, and it gets consumed without being placed.

Idk if it's only if an obstacle prevents me to build it myself, and the bots try to build it, which somehow deletes the dome.

**Comment by lukaseder** [comment] 2024-12-09 16:05
Perhaps this is the same bug as this one? https://github.com/notnotmelon/maraxsis/issues/92

**Comment by notnotmelon** [comment] 2024-12-09 16:31
Very likely the dome is not deleted. There should be an item entity on the floor where the dome was constructed.

**Comment by YarrikV** [comment] 2024-12-09 16:45
There's nothing there. I'll try to get a video

**Comment by YarrikV** [comment] 2024-12-09 16:51
This works maybe: https://youtu.be/sHa4sdnQ1pk

**Comment by notnotmelon** [comment] 2024-12-09 17:07
I see the problem. You are on an old version. This issue was actually a duplicate of https://github.com/notnotmelon/maraxsis/issues/59

**Closed by notnotmelon** 2024-12-09 17:07 UTC
