### ISSUE TITLE
[24.12.10] [FEAT] Improve briefing for dumb

### ISSUE THREAD

**Issue by Fr-Dae** [notnotmelon/maraxsis#115] opened 2024-12-10 01:27 UTC
try to make the briefing more detailed, explaining the key stages or important production/items.
Possibly in several sub-chapters to avoid spoilers, so people won't come and read them unless they're stuck on the next step.

Between the bugs, the lack of certain resources and the lack of information, it's a bit complex to deal with it when you have only two functional neurons.

**Comment by solarcloud7** [comment] 2024-12-10 18:38
Improving the story to help bridge that steep learning curve is important.     Maybe we can begin the conversation with phase 1, creating a list areas of Maraxsis that are not too noob friendly.    And then phase 2, brain storm ways to help new ones overcome those hurdles using a variety of methods that trickle knowledge in consumable pieces.  

Here is the rough draft of potential pain points I see:

- Is the trench a moon of maraxis?  How does a new player get there when they land there for the first time.
- how and what are your first resources to find on maraxsis and how/where do you find them.
- hydro reactor is most important tool required to process path of saline water -> brackish water -> salt
- Why can't i build crap on sand?  What the heck is a pressure dome.  
- Where can I get atmosphere?
- What's the item path to get plastic, oil
- Example how to program submarines to transport items  to/from trench

Something I think that would help new players is help them have proper expectations.
- you CAN NOT just raw dog Maraxsis.   You need a steady supply of resources from other planets to get established at first.
- YES quality surplus issues can be mitigated through engineering.    Its a feature not a bug.
- Platform travel to Maraxis is similar to Aquilla in that it needs rockets.

Ideas on how to teach that:
- Factopedia -  Easy to miss a description on an item.  Important instructions/ non intuitive process/ or new concepts may not be best placed here.    Reference for item stats, boiler plate descriptions are perfect here.    For example controls for a submarine to enter the trench (control + enter) may not be best place for factopedia
- Achievements - Perfect for short actions like,   "Staying Glassy" - Mine first glass from mullusk husk",  "Pound Sand" - place first drill on any sand tile to get sand", "Get Trenched - after finding trench entrance (dark tiles) in a submarine,  press control  + enter"   Usually achievements are created in a way NOT to have any dependencies on other achievements nor designed to be completed in a predetermined order. 
- Quests/ Story -  This is IMO the gold standard to teach by action with guidance that feels natural and unforced.   here would be some cool quest ideas to introduce new concepts to the game:
"Find the abandoned submarine"  -  [park an abandoned working sub with enough light oil to drop to the trench with enough torpedos to kill ONLY 1 enemy].  When the player enters the sub,  continue the story, "Huh i wonder what killed  the crew?!  While exploring the submarine controls you see a message flash on a monitor   'Danger -  multiple anomalies detected detected below!'.   Next to the monitor you see a lever that's labeled, "Descend = control  + enter".   What do you do next?  do you pull it?"  Then when the submarine descends,  spawn exactly 1 enemy that instantly is already on top of the submarine attacking it.

**Comment by notnotmelon** [comment] 2024-12-17 01:26
> To add...
> 
> Maraxsis does require the first 3 planets to be completed and can be unlocked the same time as aquilo, but it still might not be obvious to a player that planetary logistics is required. I have attached the aquilo tips and tricks for our reference in solving this.
> 
> (sorry for the brightness, windows snip tool doesnt like capturing HDR content for some reason) <img alt="image" width="1088" src="https://private-user-images.githubusercontent.com/4522226/394457991-6590fb27-977d-44bc-9312-8e70e87068a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzOTg5MDUsIm5iZiI6MTczNDM5ODYwNSwicGF0aCI6Ii80NTIyMjI2LzM5NDQ1Nzk5MS02NTkwZmIyNy05NzdkLTQ0YmMtOTMxMi04ZTcwZTg3MDY4YTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTdUMDEyMzI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Yjg1NDg3NGMzYTM3YzdlZTMyYWZlNTUxNjZiODY0Mjg3MDAyYmVkZmRhZDQ4NDQ4ZDYyMjZmNGZiODg0M2Q2NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.L9CeO-nF49E4mKL_CpAsXJV4E9xZrcjtnniG3UORMpk">

This one is now fixed, thanks for the suggestion.

![image](https://github.com/user-attachments/assets/86930e26-7086-455d-9574-0bdfb3421ebf)

**Closed** 2024-12-17 04:05 UTC

**Comment by notnotmelon** [comment] 2024-12-17 04:08
Thanks for the report. Over the last few weeks I have greatly increased the user experience through localized descriptions, tips and tricks, and other means. Today I watched a 5hr Krydax stream where most of the mechanics were flawlessly learned. All that effort seems to be paying off.

The last communication problem was having two seperate mods both performing spidertron logistics.
With the removal of construction continued, I am marking this one as resolved.
