### ISSUE TITLE
[24.12.15] [BUG] (or not ?) duplicat hydro

### ISSUE THREAD

**Issue by Fr-Dae** [notnotmelon/maraxsis#160] opened 2024-12-15 20:46 UTC
- maraxsis_1.23.46
- Facotrio Version: 2.0.25
- in upgrade planner i see 2 same icone of  hydro factory, why 2 ?

- one with 4 slot of module
- and one with 6 slot of modules

**Comment by notnotmelon** [comment] 2024-12-15 20:57
Thanks for the report. The hydro plant with extra module slots is used in the trench. There are actually two hydro plant prototypes.

The upgrade planner must show both in order to allow the user to upgrade hydro plants from within the trench. For this reason I believe this report can be marked as not a bug.

**Comment by Fr-Dae** [comment] 2024-12-15 21:07
maybe rename the second on "MKII" or "ADV"
and add a description like "in trench, it's better" for the MKI

**Closed** 2024-12-15 21:11 UTC
Labels: bug
